apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving
  namespace: model-serving
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: model-serving
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      containers:
        - name: model-serving
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: {{ .Values.mlflow.trackingUri }}
            - name: MODEL_NAME
              value: {{ .Values.mlflow.modelName }}
            - name: MODEL_STAGE
              value: {{ .Values.mlflow.modelStage }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}