apiVersion: v1
kind: Service
metadata:
  name: model-serving
  namespace: model-serving
spec:
  selector:
    app: model-serving
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: 8000
    - name: gradio
      port: 7860
      targetPort: 7860
  type: {{ .Values.service.type }}