apiVersion: v2
name: mlflow
description: MLflow tracking server
type: application
version: 0.1.0
appVersion: "2.11.0"

dependencies:
  - name: mlflow
    version: "1.0.15"
    repository: "https://community-charts.github.io/helm-charts"