mlflow:
  # Backend store — S3
  artifactRoot: s3://mlops-mlflow-artifacts/mlflow

  # Database (postgres — RDS later, sqlite for now)
  backendStore:
    databaseMigration: true
    sqlite:
      enabled: true
      path: /mlflow/data/mlflow.db

  # Storage
  persistence:
    enabled: true
    size: 10Gi

  # Ingress
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: mlflow.mlops.local
        paths:
          - path: /
            pathType: Prefix


  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"