kube-prometheus-stack:

  # Prometheus
  prometheus:
    prometheusSpec:
      retention: 7d       # 7 days retention
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"

  # Grafana
  grafana:
    adminPassword: "mlops-admin"  # password  admin 

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.mlops.local

    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "300m"

  # AlertManager
  alertmanager:
    enabled: false    # wait for alerting rules i will do later

  # Node exporter — metrics dyal nodes
  nodeExporter:
    enabled: true

  # Kube state metrics — metrics dyal pods
  kubeStateMetrics:
    enabled: true