image:
  repository: 709598629349.dkr.ecr.eu-west-1.amazonaws.com/model-serving
  tag: "174f2abc60f17df0a6a3a628aab01db1a4b14de7"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: api.aae4379a180fe4e0a87291fca6d2c3b6-b9106ea2bd7f4cb6.elb.eu-west-1.amazonaws.com
      paths:
        - path: /
          pathType: Prefix
          port: 8000
    - host: gradio.34.240.135.188.nip.io
      paths:
        - path: /
          pathType: Prefix

mlflow:
  trackingUri: "http://mlflow.mlflow.svc.cluster.local:5000"
  modelName: "MyModel"
  modelStage: "Production"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"