apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: "0.7.19"
    helm:
      values: |
        artifactRoot:
          s3:
            enabled: true
            bucket: mlops-mlflow-artifacts-709598629349
            path: mlflow
        service:
          type: ClusterIP
          port: 5000
        ingress:
          enabled: true
          ClassName: nginx
          hosts:
            - host: mlflow.mlops.local
              paths:
                - path: /
                  pathType: Prefix
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true